DESIGN_NAME: croc_chip
CLOCK_PORT: clk_i
CLOCK_PERIOD: 100
USE_SLANG: true

FP_SIZING: absolute
DIE_AREA:  [   0.00,   0.00, 2200.00, 2200.00]
CORE_AREA: [ 362, 362, 1838, 1838]
PL_TARGET_DENSITY_PCT: 50

# Bondpad is not yet included in the PDK
EXTRA_GDS:
- dir::ip/bondpad_70x70/bondpad_70x70.gds

EXTRA_LEFS:
- dir::ip/bondpad_70x70/bondpad_70x70.lef

SLANG_ARGUMENTS: ['--allow-use-before-declare']

LINTER_DISABLE_WARNINGS:
- ASSIGNIN

MACROS:
  RM_IHPSG13_1P_256x64_c2_bm_bist:

    gds: 
    - dir::sram/RM_IHPSG13_1P_256x64_c2_bm_bist.gds
    lef: 
    - pdk_dir::libs.ref/sg13g2_sram/lef/RM_IHPSG13_1P_256x64_c2_bm_bist.lef 
    nl: 
    - pdk_dir::libs.ref/sg13g2_sram/verilog/RM_IHPSG13_1P_256x64_c2_bm_bist.v
    lib: 
      "nom_typ_1p20V_25C": 
      - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_256x64_c2_bm_bist_typ_1p20V_25C.lib
      "nom_fast_1p32V_m40C": 
      - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_256x64_c2_bm_bist_fast_1p32V_m55C.lib
      "nom_slow_1p08V_125C": 
      - pdk_dir::libs.ref/sg13g2_sram/lib/RM_IHPSG13_1P_256x64_c2_bm_bist_slow_1p08V_125C.lib
    instances:
      i_croc_soc.i_croc.gen_sram_bank[0].i_sram.gen_512x32xBx1.i_cut:
        location: [1575, 700]
        orientation: E
      i_croc_soc.i_croc.gen_sram_bank[1].i_sram.gen_512x32xBx1.i_cut:
        location: [1710, 700]
        orientation: E

PAD_SOUTH: [
  pad_clk_i,
  pad_rst_ni,
  pad_ref_clk_i,
  pad_jtag_tck_i,
  pad_jtag_trst_ni,
  pad_jtag_tms_i,
  pad_jtag_tdi_i,
  pad_jtag_tdo_o,
  pad_uart_rx_i,
  pad_uart_tx_o,
  pad_fetch_en_i,
  pad_status_o,
  pad_gpio0_io,
  pad_gpio1_io,
  pad_gpio2_io,
  pad_gpio3_io,
]

PAD_EAST: [
  pad_gpio4_io,
  pad_gpio5_io,
  pad_gpio6_io,
  pad_gpio7_io,
  pad_gpio8_io,
  pad_gpio9_io,
  pad_gpio10_io,
  pad_gpio11_io,
  pad_gpio12_io,
  pad_gpio13_io,
  pad_gpio14_io,
  pad_gpio15_io,
  pad_gpio16_io,
  pad_gpio17_io,
  pad_gpio18_io,
  pad_gpio19_io,
]

PAD_NORTH: [
  pad_gpio20_io,
  pad_gpio21_io,
  pad_gpio22_io,
  pad_gpio23_io,
  pad_gpio24_io,
  pad_gpio25_io,
  pad_gpio26_io,
  pad_gpio27_io,
  pad_gpio28_io,
  pad_gpio29_io,
  pad_gpio30_io,
  pad_gpio31_io,
  pad_unused0_o,
  pad_unused1_o,
  pad_unused2_o,
  pad_unused3_o,
]

PAD_WEST: [
  pad_vdd0,
  pad_vss0,
  pad_vdd1,
  pad_vss1,
  pad_vdd2,
  pad_vss2,
  pad_vdd3,
  pad_vss3,
  pad_vddio0,
  pad_vssio0,
  pad_vddio1,
  pad_vssio1,
  pad_vddio2,
  pad_vssio2,
  pad_vddio3,
  pad_vssio3,
]


meta:
  version: 3
  flow: Chip
  substituting_steps:
    Checker.YosysSynthChecks: null
    # Magic always fails DRC, so we disable it here
    Magic.DRC: null
    KLayout.DRC: null
    Checker.DisconnectedPins: null
    KLayout.Antenna: null
    KLayout.Filler: null
    Magic.SpiceExtraction: null
    Checker.KLayoutDensity: null
    Netgen.LVS: null

VERILOG_DEFINES:
- TARGET_ASIC
- TARGET_IHP13
- TARGET_RTL
- TARGET_SYNTHESIS
- VERILATOR=1
- SYNTHESIS=1
- COMMON_CELLS_ASSERTS_OFF=1
- FUNCTIONAL

VERILOG_INCLUDE_DIRS: 
- ../../croc/rtl/apb/include
- ../../croc/rtl/common_cells/include
- ../../croc/rtl/cve2/include
- ../../croc/rtl/obi/include
- ../../croc/rtl/register_interface/include
    
VERILOG_FILES: 
- ../../croc/rtl/common_cells/binary_to_gray.sv
- ../../croc/rtl/common_cells/cb_filter_pkg.sv
- ../../croc/rtl/common_cells/cc_onehot.sv
- ../../croc/rtl/common_cells/cdc_reset_ctrlr_pkg.sv
- ../../croc/rtl/common_cells/cf_math_pkg.sv
- ../../croc/rtl/common_cells/clk_int_div.sv
- ../../croc/rtl/common_cells/credit_counter.sv
- ../../croc/rtl/common_cells/delta_counter.sv
- ../../croc/rtl/common_cells/ecc_pkg.sv
- ../../croc/rtl/common_cells/edge_propagator_tx.sv
- ../../croc/rtl/common_cells/exp_backoff.sv
- ../../croc/rtl/common_cells/fifo_v3.sv
- ../../croc/rtl/common_cells/gray_to_binary.sv
- ../../croc/rtl/common_cells/isochronous_4phase_handshake.sv
- ../../croc/rtl/common_cells/isochronous_spill_register.sv
- ../../croc/rtl/common_cells/lfsr.sv
- ../../croc/rtl/common_cells/lfsr_16bit.sv
- ../../croc/rtl/common_cells/lfsr_8bit.sv
- ../../croc/rtl/common_cells/lossy_valid_to_stream.sv
- ../../croc/rtl/common_cells/mv_filter.sv
- ../../croc/rtl/common_cells/onehot_to_bin.sv
- ../../croc/rtl/common_cells/plru_tree.sv
- ../../croc/rtl/common_cells/passthrough_stream_fifo.sv
- ../../croc/rtl/common_cells/popcount.sv
- ../../croc/rtl/common_cells/rr_arb_tree.sv
- ../../croc/rtl/common_cells/rstgen_bypass.sv
- ../../croc/rtl/common_cells/serial_deglitch.sv
- ../../croc/rtl/common_cells/shift_reg.sv
- ../../croc/rtl/common_cells/shift_reg_gated.sv
- ../../croc/rtl/common_cells/spill_register_flushable.sv
- ../../croc/rtl/common_cells/stream_demux.sv
- ../../croc/rtl/common_cells/stream_filter.sv
- ../../croc/rtl/common_cells/stream_fork.sv
- ../../croc/rtl/common_cells/stream_intf.sv
- ../../croc/rtl/common_cells/stream_join_dynamic.sv
- ../../croc/rtl/common_cells/stream_mux.sv
- ../../croc/rtl/common_cells/stream_throttle.sv
- ../../croc/rtl/common_cells/sub_per_hash.sv
- ../../croc/rtl/common_cells/sync.sv
- ../../croc/rtl/common_cells/sync_wedge.sv
- ../../croc/rtl/common_cells/unread.sv
- ../../croc/rtl/common_cells/read.sv
- ../../croc/rtl/common_cells/addr_decode_dync.sv
- ../../croc/rtl/common_cells/cdc_2phase.sv
- ../../croc/rtl/common_cells/cdc_4phase.sv
- ../../croc/rtl/common_cells/clk_int_div_static.sv
- ../../croc/rtl/common_cells/addr_decode.sv
- ../../croc/rtl/common_cells/addr_decode_napot.sv
- ../../croc/rtl/common_cells/multiaddr_decode.sv
- ../../croc/rtl/common_cells/cb_filter.sv
- ../../croc/rtl/common_cells/cdc_fifo_2phase.sv
- ../../croc/rtl/common_cells/clk_mux_glitch_free.sv
- ../../croc/rtl/common_cells/counter.sv
- ../../croc/rtl/common_cells/ecc_decode.sv
- ../../croc/rtl/common_cells/ecc_encode.sv
- ../../croc/rtl/common_cells/edge_detect.sv
- ../../croc/rtl/common_cells/lzc.sv
- ../../croc/rtl/common_cells/max_counter.sv
- ../../croc/rtl/common_cells/rstgen.sv
- ../../croc/rtl/common_cells/spill_register.sv
- ../../croc/rtl/common_cells/stream_delay.sv
- ../../croc/rtl/common_cells/stream_fifo.sv
- ../../croc/rtl/common_cells/stream_fork_dynamic.sv
- ../../croc/rtl/common_cells/stream_join.sv
- ../../croc/rtl/common_cells/cdc_reset_ctrlr.sv
- ../../croc/rtl/common_cells/cdc_fifo_gray.sv
- ../../croc/rtl/common_cells/fall_through_register.sv
- ../../croc/rtl/common_cells/id_queue.sv
- ../../croc/rtl/common_cells/stream_to_mem.sv
- ../../croc/rtl/common_cells/stream_arbiter_flushable.sv
- ../../croc/rtl/common_cells/stream_fifo_optimal_wrap.sv
- ../../croc/rtl/common_cells/stream_register.sv
- ../../croc/rtl/common_cells/stream_xbar.sv
- ../../croc/rtl/common_cells/cdc_fifo_gray_clearable.sv
- ../../croc/rtl/common_cells/cdc_2phase_clearable.sv
- ../../croc/rtl/common_cells/mem_to_banks_detailed.sv
- ../../croc/rtl/common_cells/stream_arbiter.sv
- ../../croc/rtl/common_cells/stream_omega_net.sv
- ../../croc/rtl/common_cells/mem_to_banks.sv
- ../../croc/rtl/apb/apb_pkg.sv
- ../../croc/rtl/obi/obi_pkg.sv
- ../../croc/rtl/obi/obi_intf.sv
- ../../croc/rtl/obi/obi_rready_converter.sv
- ../../croc/rtl/obi/obi_atop_resolver.sv
- ../../croc/rtl/obi/obi_cut.sv
- ../../croc/rtl/obi/obi_demux.sv
- ../../croc/rtl/obi/obi_err_sbr.sv
- ../../croc/rtl/obi/obi_mux.sv
- ../../croc/rtl/obi/obi_sram_shim.sv
- ../../croc/rtl/obi/obi_xbar.sv
- ../../croc/rtl/cve2/cve2_pkg.sv
- ../../croc/rtl/cve2/cve2_alu.sv
- ../../croc/rtl/cve2/cve2_compressed_decoder.sv
- ../../croc/rtl/cve2/cve2_controller.sv
- ../../croc/rtl/cve2/cve2_counter.sv
- ../../croc/rtl/cve2/cve2_csr.sv
- ../../croc/rtl/cve2/cve2_decoder.sv
- ../../croc/rtl/cve2/cve2_fetch_fifo.sv
- ../../croc/rtl/cve2/cve2_load_store_unit.sv
- ../../croc/rtl/cve2/cve2_multdiv_fast.sv
- ../../croc/rtl/cve2/cve2_multdiv_slow.sv
- ../../croc/rtl/cve2/cve2_pmp.sv
- ../../croc/rtl/cve2/cve2_register_file_ff.sv
- ../../croc/rtl/cve2/cve2_wb.sv
- ../../croc/rtl/cve2/cve2_cs_registers.sv
- ../../croc/rtl/cve2/cve2_ex_block.sv
- ../../croc/rtl/cve2/cve2_id_stage.sv
- ../../croc/rtl/cve2/cve2_prefetch_buffer.sv
- ../../croc/rtl/cve2/cve2_if_stage.sv
- ../../croc/rtl/cve2/cve2_core.sv
- ../../croc/rtl/obi_uart/obi_uart_pkg.sv
- ../../croc/rtl/obi_uart/obi_uart_baudgen.sv
- ../../croc/rtl/obi_uart/obi_uart_interrupts.sv
- ../../croc/rtl/obi_uart/obi_uart_modem.sv
- ../../croc/rtl/obi_uart/obi_uart_rx.sv
- ../../croc/rtl/obi_uart/obi_uart_tx.sv
- ../../croc/rtl/obi_uart/obi_uart_register.sv
- ../../croc/rtl/obi_uart/obi_uart.sv
- ../../croc/rtl/register_interface/reg_intf.sv
- ../../croc/rtl/register_interface/lowrisc_opentitan/prim_subreg_arb.sv
- ../../croc/rtl/register_interface/lowrisc_opentitan/prim_subreg_ext.sv
- ../../croc/rtl/register_interface/periph_to_reg.sv
- ../../croc/rtl/register_interface/reg_to_apb.sv
- ../../croc/rtl/register_interface/lowrisc_opentitan/prim_subreg_shadow.sv
- ../../croc/rtl/register_interface/lowrisc_opentitan/prim_subreg.sv
- ../../croc/rtl/riscv-dbg/dm_pkg.sv
- ../../croc/rtl/riscv-dbg/debug_rom/debug_rom.sv
- ../../croc/rtl/riscv-dbg/debug_rom/debug_rom_one_scratch.sv
- ../../croc/rtl/riscv-dbg/dm_csrs.sv
- ../../croc/rtl/riscv-dbg/dm_mem.sv
- ../../croc/rtl/riscv-dbg/dmi_cdc.sv
- ../../croc/rtl/riscv-dbg/dmi_jtag_tap.sv
- ../../croc/rtl/riscv-dbg/dm_sba.sv
- ../../croc/rtl/riscv-dbg/dm_top.sv
- ../../croc/rtl/riscv-dbg/dmi_jtag.sv
- ../../croc/rtl/riscv-dbg/dm_obi_top.sv
- ../../croc/rtl/timer_unit/timer_unit_counter.sv
- ../../croc/rtl/timer_unit/timer_unit_counter_presc.sv
- ../../croc/rtl/timer_unit/apb_timer_unit.sv
- ../../croc/rtl/timer_unit/timer_unit.sv
- ../../croc/ihp13/tc_clk.sv
- ../../croc/ihp13/tc_sram_impl.sv
- ../../croc/rtl/croc_pkg.sv
- ../../croc/rtl/user_pkg.sv
- ../../croc/rtl/soc_ctrl/soc_ctrl_regs_pkg.sv
- ../../croc/rtl/gpio/gpio_reg_pkg.sv
- ../../croc/rtl/core_wrap.sv
- ../../croc/rtl/soc_ctrl/soc_ctrl_regs.sv
- ../../croc/rtl/gpio/gpio_reg_top.sv 
- ../../croc/rtl/gpio/gpio.sv
- ../../croc/rtl/croc_domain.sv
- ../../croc/rtl/croc_chip.sv
- ../../croc/rtl/croc_soc.sv
- ../../croc/rtl/user_domain.sv

